### ISSUE TITLE
I am trying to create an HTML report, but it doesnt do so

### ISSUE THREAD

**Issue by sarath-baskar** [CiscoTestAutomation/pyats#101]
Caught error in plugin 'HTMLLogsPlugin':
2021-05-20T17:59:44: %EASYPY-ERROR: 
2021-05-20T17:59:44: %EASYPY-ERROR: Traceback (most recent call last):
2021-05-20T17:59:44: %EASYPY-ERROR:   File "src/pyats/easypy/plugins/htmllogs.py", line 114, in pyats.easypy.plugins.htmllogs.HTMLLogsPlugin.post_job

**Comment by sarath-baskar** [comment]
I was executing the basic cases of pyATS which was cloned from pyATS git hub.
pyATS version 21.5
python version 3.6.9

Aetest Common Cleanup 
2021-05-20T23:05:15: %AETEST-INFO: The result of subsection clean_everything is => PASSED
2021-05-20T23:05:15: %AETEST-INFO: The result of common cleanup is => PASSED
2021-05-20T23:05:15: %CONTRIB-INFO: WebEx Token not given as argument or in config. No WebEx notification will be sent
2021-05-20T23:05:15: %EASYPY-INFO: Generating HTML report file
2021-05-20T23:05:15: %EASYPY-ERROR: Caught error in plugin 'HTMLLogsPlugin':
2021-05-20T23:05:15: %EASYPY-ERROR: 
2021-05-20T23:05:15: %EASYPY-ERROR: Traceback (most recent call last):
2021-05-20T23:05:15: %EASYPY-ERROR:   File "src/pyats/easypy/plugins/htmllogs.py", line 114, in pyats.easypy.plugins.htmllogs.HTMLLogsPlugin.post_job
2021-05-20T23:05:15: %EASYPY-ERROR:   File "/home/cnwave/pyats/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
2021-05-20T23:05:15: %EASYPY-ERROR:     self.environment.handle_exception()
2021-05-20T23:05:15: %EASYPY-ERROR:   File "/home/cnwave/pyats/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
2021-05-20T23:05:15: %EASYPY-ERROR:     reraise(*rewrite_traceback_stack(source=source))
2021-05-20T23:05:15: %EASYPY-ERROR:   File "/home/cnwave/pyats/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
2021-05-20T23:05:15: %EASYPY-ERROR:     raise value.with_traceback(tb)
2021-05-20T23:05:15: %EASYPY-ERROR:   File "/home/cnwave/pyats/lib/python3.6/site-packages/pyats/easypy/templates/log_view_template.html", line 51, in top-level template code
2021-05-20T23:05:15: %EASYPY-ERROR:     {% for script in testsuite.testscripts %}
2021-05-20T23:05:15: %EASYPY-ERROR:   File "/home/cnwave/pyats/lib/python3.6/site-packages/jinja2/runtime.py", line 403, in __init__
2021-05-20T23:05:15: %EASYPY-ERROR:     self._iterator = self._to_iterator(iterable)
2021-05-20T23:05:15: %EASYPY-ERROR:   File "/home/cnwave/pyats/lib/python3.6/site-packages/jinja2/runtime.py", line 411, in _to_iterator
2021-05-20T23:05:15: %EASYPY-ERROR:     return iter(iterable)
2021-05-20T23:05:15: %EASYPY-ERROR: TypeError: 'NoneType' object is not iterable
2021-05-20T23:05:15: %EASYPY-INFO: --------------------------------------------------------------------------------
2021-05-20T23:05:15: %EASYPY-INFO: Job finished. Wrapping up...
2021-05-20T23:05:15: %EASYPY-ERROR: Caught 1 or more error in Easypy plugins:
2021-05-20T23:05:15: %EASYPY-ERROR: HTMLLogsPlugin[post_job] Traceback (most recent call last):
2021-05-20T23:05:15: %EASYPY-ERROR:   File "src/pyats/easypy/plugins/htmllogs.py", line 114, in pyats.easypy.plugins.htmllogs.HTMLLogsPlugin.post_job
2021-05-20T23:05:15: %EASYPY-ERROR:   File "/home/cnwave/pyats/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
2021-05-20T23:05:15: %EASYPY-ERROR:     self.environment.handle_exception()
2021-05-20T23:05:15: %EASYPY-ERROR:   File "/home/cnwave/pyats/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
2021-05-20T23:05:15: %EASYPY-ERROR:     reraise(*rewrite_traceback_stack(source=source))
2021-05-20T23:05:15: %EASYPY-ERROR:   File "/home/cnwave/pyats/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
2021-05-20T23:05:15: %EASYPY-ERROR:     raise value.with_traceback(tb)
2021-05-20T23:05:15: %EASYPY-ERROR:   File "/home/cnwave/pyats/lib/python3.6/site-packages/pyats/easypy/templates/log_view_template.html", line 51, in top-level template code
2021-05-20T23:05:15: %EASYPY-ERROR:     {% for script in testsuite.testscripts %}
2021-05-20T23:05:15: %EASYPY-ERROR:   File "/home/cnwave/pyats/lib/python3.6/site-packages/jinja2/runtime.py", line 403, in __init__
2021-05-20T23:05:15: %EASYPY-ERROR:     self._iterator = self._to_iterator(iterable)
2021-05-20T23:05:15: %EASYPY-ERROR:   File "/home/cnwave/pyats/lib/python3.6/site-packages/jinja2/runtime.py", line 411, in _to_iterator
2021-05-20T23:05:15: %EASYPY-ERROR:     return iter(iterable)
2021-05-20T23:05:15: %EASYPY-ERROR: TypeError: 'NoneType' object is not iterable
2021-05-20T23:05:15: %EASYPY-INFO: Creating archive file: /home/cnwave/.pyats/archive/21-May/basic_example_job.2021May20_23:05:12.289251.zip
2021-05-20T23:05:15: %EASYPY-INFO: +------------------------------------------------------------------------------+
2021-05-20T23:05:15: %EASYPY-INFO: |                          !!! Plugin Exceptions !!!                           |
2021-05-20T23:05:15: %EASYPY-INFO: +------------------------------------------------------------------------------+
2021-05-20T23:05:15: %EASYPY-INFO: Caught 1 or more error in Easypy plugins:
2021-05-20T23:05:15: %EASYPY-INFO: HTMLLogsPlugin[post_job] Traceback (most recent call last):
2021-05-20T23:05:15: %EASYPY-INFO:   File "src/pyats/easypy/plugins/htmllogs.py", line 114, in pyats.easypy.plugins.htmllogs.HTMLLogsPlugin.post_job
2021-05-20T23:05:15: %EASYPY-INFO:   File "/home/cnwave/pyats/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
2021-05-20T23:05:15: %EASYPY-INFO:     self.environment.handle_exception()
2021-05-20T23:05:15: %EASYPY-INFO:   File "/home/cnwave/pyats/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
2021-05-20T23:05:15: %EASYPY-INFO:     reraise(*rewrite_traceback_stack(source=source))
2021-05-20T23:05:15: %EASYPY-INFO:   File "/home/cnwave/pyats/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
2021-05-20T23:05:15: %EASYPY-INFO:     raise value.with_traceback(tb)
2021-05-20T23:05:15: %EASYPY-INFO:   File "/home/cnwave/pyats/lib/python3.6/site-packages/pyats/easypy/templates/log_view_template.html", line 51, in top-level template code
2021-05-20T23:05:15: %EASYPY-INFO:     {% for script in testsuite.testscripts %}
2021-05-20T23:05:15: %EASYPY-INFO:   File "/home/cnwave/pyats/lib/python3.6/site-packages/jinja2/runtime.py", line 403, in __init__
2021-05-20T23:05:15: %EASYPY-INFO:     self._iterator = self._to_iterator(iterable)
2021-05-20T23:05:15: %EASYPY-INFO:   File "/home/cnwave/pyats/lib/python3.6/site-packages/jinja2/runtime.py", line 411, in _to_iterator
2021-05-20T23:05:15: %EASYPY-INFO:     return iter(iterable)
2021-05-20T23:05:15: %EASYPY-INFO: TypeError: 'NoneType' object is not iterable

**Comment by jeaubin** [comment]
html-log has been replaced with the latest command - pyats logs view 

the html logs has deprecated a few years ago

**Comment by sarath-baskar** [comment]
Thanks!!!
Is there a way can we download the logs as a html file ?
