### ISSUE TITLE
Version Update fails for full install

### ISSUE THREAD

**Issue by hdinthkld** [CiscoTestAutomation/pyats#115]
When running the 'pyats version update' command, pip fails with the output:
Uninstalling existing packages...
Installing new packages...

Command 'pip3 install --disable-pip-version-check pyats[full]' returned non-zero exit status 1.

Running the command manually reports:
ERROR: Could not find a version that satisfies the requirement pyats.contrib<21.7.0,>=21.6.0; extra == "full" (from pyats[full]) (from versions: 20.4, 20.4.1, 20.4.2, 20.5, 20.6, 20.6.1, 20.7, 20.8, 20.8.1b0, 20.9, 20.9.1b0, 20.10, 20.10.1, 20.10.2, 20.10.3, 20.12, 20.12.1, 20.12.2b0, 21.1, 21.2, 21.3, 21.4, 21.5)
ERROR: No matching distribution found for pyats.contrib<21.7.0,>=21.6.0; extra == "full" (from pyats[full])

Previously running in virtual environment with PyATS installed through:
pip install pyats[library]

The same command is required to reinstall the environment after the failure.

Attempting to run "full" install in a new virtual environment reports same error as above. 

Running inside Ubuntu docker container with versions:
pyATS version: 21.6
Python: 3.8.5 [64bit]
pip 20.0.2 
Linux 3.10.0-1160.24.1.el7.x86_64 #1 SMP

**Comment by lsheikal** [comment]
Kindly create a new virtual environment, update pip and do ``pip install pyats[full]`` and post the full log of installation or error which you are facing.

**Comment by krishna1306** [comment]
This is the full log of errors I am getting when I tried to install pyats[full] in a virtual environment. `pip` is updated before attempting pyats install

```
Collecting pyats.log<23.2.0,>=23.1.0
  Downloading pyats.log-23.1-cp310-cp310-macosx_11_0_x86_64.whl (8.2 MB)
     ━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/8.2 MB 16.0 MB/s eta 0:00:01
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 465, in read
    s = self.fp.read(amt)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 415, in run
    requirement_set = resolver.resolve(
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
    with self._error_catcher():
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
 krishnabandi@KRIBANDI-M-X0Q2  ~/Documents/Learning/learn-genie/CL-DevNet-2595   master  pip install 'pyATS[full]'                 2 ↵  venv

Collecting pyATS[full]
  Using cached pyats-23.1-cp310-cp310-macosx_11_0_x86_64.whl (864 kB)
Collecting pyats.reporter<23.2.0,>=23.1.0
  Downloading pyats.reporter-23.1-cp310-cp310-macosx_11_0_x86_64.whl (730 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 730.8/730.8 kB 1.8 MB/s eta 0:00:00
Collecting packaging>=20.0
  Using cached packaging-23.0-py3-none-any.whl (42 kB)
Collecting pyats.results<23.2.0,>=23.1.0
  Downloading pyats.results-23.1-cp310-cp310-macosx_11_0_x86_64.whl (115 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.6/115.6 kB 943.9 kB/s eta 0:00:00
Collecting pyats.utils<23.2.0,>=23.1.0
  Using cached pyats.utils-23.1-cp310-cp310-macosx_11_0_x86_64.whl (1.6 MB)
Collecting pyats.connections<23.2.0,>=23.1.0
  Downloading pyats.connections-23.1-cp310-cp310-macosx_11_0_x86_64.whl (204 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.9/204.9 kB 1.1 MB/s eta 0:00:00
Collecting pyats.async<23.2.0,>=23.1.0
  Using cached pyats.async-23.1-cp310-cp310-macosx_11_0_x86_64.whl (128 kB)
Collecting pyats.easypy<23.2.0,>=23.1.0
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/0b/4a/0a6077b1058991b7aaf5ec3f43407a342d3bc4ee71c422d0f5916450cf13/pyats.easypy-23.1-cp310-cp310-macosx_11_0_x86_64.whl
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/0b/4a/0a6077b1058991b7aaf5ec3f43407a342d3bc4ee71c422d0f5916450cf13/pyats.easypy-23.1-cp310-cp310-macosx_11_0_x86_64.whl
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/0b/4a/0a6077b1058991b7aaf5ec3f43407a342d3bc4ee71c422d0f5916450cf13/pyats.easypy-23.1-cp310-cp310-macosx_11_0_x86_64.whl
  Downloading pyats.easypy-23.1-cp310-cp310-macosx_11_0_x86_64.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 470.4 kB/s eta 0:00:00
Collecting pyats.aetest<23.2.0,>=23.1.0
  Downloading pyats.aetest-23.1-cp310-cp310-macosx_11_0_x86_64.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 13.4 MB/s eta 0:00:00
Collecting pyats.topology<23.2.0,>=23.1.0
  Using cached pyats.topology-23.1-cp310-cp310-macosx_11_0_x86_64.whl (656 kB)
Collecting pyats.aereport<23.2.0,>=23.1.0
  Using cached pyats.aereport-23.1-cp310-cp310-macosx_11_0_x86_64.whl (2.0 MB)
Collecting pyats.kleenex<23.2.0,>=23.1.0
  Using cached pyats.kleenex-23.1-cp310-cp310-macosx_11_0_x86_64.whl (1.3 MB)
Collecting pyats.tcl<23.2.0,>=23.1.0
  Using cached pyats.tcl-23.1-cp310-cp310-macosx_11_0_x86_64.whl (545 kB)
Collecting pyats.datastructures<23.2.0,>=23.1.0
  Downloading pyats.datastructures-23.1-cp310-cp310-macosx_11_0_x86_64.whl (297 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 297.4/297.4 kB 8.9 MB/s eta 0:00:00
Collecting pyats.log<23.2.0,>=23.1.0
  Downloading pyats.log-23.1-cp310-cp310-macosx_11_0_x86_64.whl (8.2 MB)
     ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 4.2/8.2 MB 15.4 MB/s eta 0:00:01
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 465, in read
    s = self.fp.read(amt)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 415, in run
    requirement_set = resolver.resolve(
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
    with self._error_catcher():
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/krishnabandi/Documents/Learning/learn-genie/CL-DevNet-2595/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```
