### ISSUE TITLE
"show ip route summary" parser error for IOS device

### ISSUE THREAD

**Issue by icarus78** [CiscoTestAutomation/pyats#129]
Hi

I´m having errors when trying to parse the commands "show ip route summary" and "show ip route vrf <vrf> summary" with IOS devices

Find below the outputs when executing the parsing of the commands. I´ve updated to the latest pyats version (21.8), but I´m getting the same error.

Appreciate any support on this

>>> show_ip_route_summ = device.parse('show ip route summary')

2021-09-15 17:10:38,863: %UNICON-INFO: +++ HU980_05ND_CORE_A with alias 'cli': executing command 'show ip route summary' +++
show ip route summary
IP routing table name is Default-IP-Routing-Table(0)
IP routing table maximum-paths is 32
Route Source    Networks    Subnets     Overhead    Memory (bytes)
connected       2           43          9260        6480
static          6           58          19508       9216
eigrp 1         0           0           0           0
ospf 100        101         4343        351936      641980
  Intra-area: 80 Inter-area: 638 External-1: 3147 External-2: 578
  NSSA External-1: 1 NSSA External-2: 0
bgp 65448       133         72          43092       31564
  External: 0 Internal: 197 Local: 8
internal        96                                  210048
Total           338         4516        423796      899288
Removing Queue Size 0
HU980_05ND_CORE_A#
Traceback (most recent call last):
  File "<pyshell#81>", line 1, in <module>
    showw_ip_route_summ = device.parse('show ip route summary')
  File "src/genie/conf/base/device.py", line 524, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 551, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
  File "/Users/jnombert/Documents/Programming/anaconda3/lib/python3.7/site-packages/genie/libs/parser/iosxe/show_routing.py", line 1941, in cli
    vrf_rs_dict['ospf'][instance].update(group)
KeyError: None

>>> show_ip_route_summ = device.parse('show ip route vrf USUARIOS-SUC summary' )

2021-09-14 17:52:03,805: %UNICON-INFO: +++ HU980_05ND_CORE_A with alias 'cli': executing command 'show ip route vrf USUARIOS-SUC summary' +++
show ip route vrf USUARIOS-SUC summary
IP routing table name is USUARIOS-SUC(1)
IP routing table maximum-paths is 32
Route Source    Networks    Subnets     Overhead    Memory (bytes)
connected       0           25          5260        3600
static          0           0           0           0
eigrp           0           0           0           0
ospf 99         233         4464        338252      684544
  Intra-area: 356 Inter-area: 380 External-1: 3154 External-2: 807
  NSSA External-1: 0 NSSA External-2: 0
bgp 65448       0           0           0           0
  External: 0 Internal: 0 Local: 0
internal        88                                  192544
Total           321         4489        343512      880688
Removing Queue Size 0
HU980_05ND_CORE_A#
Traceback (most recent call last):
  File "<pyshell#337>", line 2, in <module>
    show_proc_cpu_hist = device.parse(command)
  File "src/genie/conf/base/device.py", line 524, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 551, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
  File "/Users/jnombert/Documents/Programming/anaconda3/lib/python3.7/site-packages/genie/libs/parser/iosxe/show_routing.py", line 1941, in cli
    vrf_rs_dict['ospf'][instance].update(group)
KeyError: None

(venv1) (base) jnombert@JNOMBERT-M-CPA5 scripts % pyats version check
You are currently running pyATS version: 21.8.1
Python: 3.7.6 [64bit]

  Package                      Version
  ---------------------------- -------
  genie                        21.8.2
  genie.libs.clean             21.8
  genie.libs.conf              21.8
  genie.libs.filetransferutils 21.8
  genie.libs.health            21.8.1
  genie.libs.ops               21.8
  genie.libs.parser            21.8
  genie.libs.robot             21.8
  genie.libs.sdk               21.8
  genie.telemetry              21.8
  genie.trafficgen             21.8.1
  pyats                        21.8.1
  pyats.aereport               21.8.1
  pyats.aetest                 21.8.1
  pyats.async                  21.8.1
  pyats.connections            21.8.1
  pyats.contrib                21.8
  pyats.datastructures         21.8.1
  pyats.easypy                 21.8.1
  pyats.kleenex                21.8.1
  pyats.log                    21.8.1
  pyats.reporter               21.8.1
  pyats.results                21.8.1
  pyats.robot                  21.8.1
  pyats.tcl                    21.8.1
  pyats.topology               21.8.1
  pyats.utils                  21.8.1
  unicon                       21.8
  unicon.plugins               21.8

Regards

**Comment by GerriorL** [comment]
Hi Icarus, thank you for submitting your issue.

Looking into it I'm noticing that the device output from your error message doesn't quite line up with what is expected from the "show ip route summary" command. Would it be possible for you to provide your device's raw output?

**Comment by icarus78** [comment]
Hi GerriorL

I´ve included the raw output of the show commands on case creation. I´m including it again, with additional details of the platform (WS-C6509-E ) and IOS version (12.2(33)SXJ2). If you require other information, please clarify.

I´ve noticed that the parse is not failing with another IOS device where the output of the show command includes an additional column ('Replicates'). Although as you say the error doesn´t line up with it also, maybe it should worth looking at it.

#### Failing Device 

HU980_05ND_CORE_A#show ip route summary 
IP routing table name is Default-IP-Routing-Table(0)
IP routing table maximum-paths is 32
Route Source    Networks    Subnets     Overhead    Memory (bytes)
connected       2           43          9260        6480
static          6           58          19508       9216
eigrp 1         0           0           0           0
ospf 100        101         4344        352008      642124
  Intra-area: 80 Inter-area: 638 External-1: 3148 External-2: 578
  NSSA External-1: 1 NSSA External-2: 0
bgp 65448       133         72          43092       31564
  External: 0 Internal: 197 Local: 8
internal        96                                  210048
Total           338         4517        423868      899432
Removing Queue Size 0
HU980_05ND_CORE_A#

HU980_05ND_CORE_A#show ip route vrf USUARIOS-SUC summary 
IP routing table name is USUARIOS-SUC(1)
IP routing table maximum-paths is 32
Route Source    Networks    Subnets     Overhead    Memory (bytes)
connected       0           25          5260        3600
static          0           0           0           0
eigrp           0           0           0           0
ospf 99         233         4467        338468      684976
  Intra-area: 357 Inter-area: 380 External-1: 3156 External-2: 807
  NSSA External-1: 0 NSSA External-2: 0
bgp 65448       0           0           0           0
  External: 0 Internal: 0 Local: 0
internal        88                                  192544
Total           321         4492        343728      881120
Removing Queue Size 0
HU980_05ND_CORE_A#


HU980_05ND_CORE_A#show version | i processor          
Uptime for this control processor is 4 years, 12 weeks, 16 hours, 41 minutes
cisco WS-C6509-E (R7000) processor (revision 1.6) with 458720K/65536K bytes of memory.
HU980_05ND_CORE_A#

HU980_05ND_CORE_A#show version | i System image
System image file is "sup-bootdisk:s72033-advipservicesk9_wan-mz.122-33.SXJ2.bin"
HU980_05ND_CORE_A#



#### Working Device 
#### HU980_05ND_RO_GTD_A (CISCO3925-CHASSIS with 151-4.M4 IOS version) 

>>> show_ip_route_summ = device.parse('show ip route summary')

2021-09-17 13:12:15,342: %UNICON-INFO: +++ HU980_05ND_RO_GTD_A with alias 'cli': executing command 'show ip route summary' +++
show ip route summary
IP routing table name is default (0x0)
IP routing table maximum-paths is 32
Route Source    Networks    Subnets     Replicates  Overhead    Memory (bytes)
connected       0           68          0           4080        11968
static          0           0           0           0           0
eigrp 120       0           54          0           4320        9504
ospf 100        0           0           0           0           0
  Intra-area: 0 Inter-area: 0 External-1: 0 External-2: 0
  NSSA External-1: 0 NSSA External-2: 0
bgp 65497       1           0           0           60          176
  External: 1 Internal: 0 Local: 0
internal        9                                               6016
Total           10          122         0           8460        27664
HU980_05ND_RO_GTD_A#
>>> 
>>> 
>>> show_ip_route_summ
{'vrf': {'default': {'vrf_id': '0x0', 'route_source': {'connected': {'networks': 0, 'subnets': 68, 'replicates': 0, 'overhead': 4080, 'memory_bytes': 11968}, 'static': {'networks': 0, 'subnets': 0, 'replicates': 0, 'overhead': 0, 'memory_bytes': 0}, 'eigrp': {'120': {'networks': 0, 'subnets': 54, 'replicates': 0, 'overhead': 4320, 'memory_bytes': 9504}}, 'ospf': {'100': {'networks': 0, 'subnets': 0, 'replicates': 0, 'overhead': 0, 'memory_bytes': 0, 'intra_area': 0, 'inter_area': 0, 'external_1': 0, 'external_2': 0, 'nssa_external_1': 0, 'nssa_external_2': 0}}, 'bgp': {'65497': {'networks': 1, 'subnets': 0, 'replicates': 0, 'overhead': 60, 'memory_bytes': 176, 'external': 1, 'internal': 0, 'local': 0}}, 'internal': {'networks': 9, 'memory_bytes': 6016}}, 'maximum_paths': 32, 'total_route_source': {'networks': 10, 'subnets': 122, 'replicates': 0, 'overhead': 8460, 'memory_bytes': 27664}}}}
>>> 

Regards

**Comment by GerriorL** [comment]
Hi Icarus,

A fix for this issue has been merged. Please look for it in the next release which will be at the end of this month.

**Comment by icarus78** [comment]
Great

Thanks GerriorL
