### ISSUE TITLE
Invalid easy_config.yaml input for plugins

### ISSUE THREAD

**Issue by hh7843175** [CiscoTestAutomation/pyats#14]
I have installed pyATS via `pip3`. I will get this error when i import `aetest`:

```
(pyats)  root ~/pytest_tmp # python3
Python 3.5.1+ (default, Mar 30 2016, 22:46:26)
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ats import aetest
Traceback (most recent call last):
  File "src/pyats/easypy/config/schema.py", line 43, in pyats.easypy.config.schema.validate_plugins
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 910, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "src/pyats/easypy/plugins/kleenex.py", line 13, in init pyats.easypy.plugins.kleenex
ImportError: cannot import name validate_clean_devices

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hamid/pyats/lib/python3.5/site-packages/pyats/aetest/__init__.py", line 31, in <module>
    from .main import main
  File "src/pyats/aetest/main.py", line 18, in init pyats.aetest.main
  File "src/pyats/aetest/utils/pause.py", line 23, in init pyats.aetest.utils.pause
  File "/home/hamid/pyats/lib/python3.5/site-packages/pyats/easypy/__init__.py", line 7, in <module>
    from .main import _default_runtime, main
  File "src/pyats/easypy/main.py", line 313, in init pyats.easypy.main
  File "src/pyats/easypy/main.py", line 97, in pyats.easypy.main.EasypyRuntime.__init__
  File "src/pyats/easypy/config/manager.py", line 61, in pyats.easypy.config.manager.Configuration.load
  File "src/pyats/utils/yaml/loader.py", line 107, in pyats.utils.yaml.loader.Loader.load
  File "src/pyats/utils/schemaengine.py", line 296, in pyats.utils.schemaengine.Schema.validate
  File "src/pyats/utils/schemaengine.py", line 293, in pyats.utils.schemaengine.Schema.validate
  File "src/pyats/utils/schemaengine.py", line 234, in pyats.utils.schemaengine.Schema.validate
  File "src/pyats/utils/schemaengine.py", line 480, in pyats.utils.schemaengine.Use.validate
  File "src/pyats/utils/schemaengine.py", line 478, in pyats.utils.schemaengine.Use.validate
  File "src/pyats/easypy/config/schema.py", line 51, in pyats.easypy.config.schema.validate_plugins
pyats.utils.exceptions.SchemaError: Invalid easy_config.yaml input for plugins
>>>

```

also, there is a big question for me, why don't you publish this best automation tools/framework as a public framework ?

**Comment by jeaubin** [comment]
Hi,

Can you do

pip install pyats.kleenex —upgrade 

Kleenex releases was delayed a bit, causing this issue.  

I am on my phone right now, will reply in a bit for the automation question. 

Let me know if this unblock you!

**Comment by siming85** [comment]
regarding open source - it's a complicated story.

if you look at the open sourced packages from say, Google, often by the time the packages are open sourced, they are no longer being used internally - and internally they've migrated to a newer, better implementation.

the difference here is that pyATS & Genie is ALWAYS up-to-date. the version you are downloading from PyPI is the exact same version as we released internally in Cisco, without delay. This is being used in millions of internal sanity, regression runs... and it's a critical infrastructure.

I would love to see everything being open sourced, and such IS the way to go, but at the moment, management is testing waters with first open sourcing the libraries (eg, Genie libs), which is already the bulk of it all. Once the process settles, everything is within a certain comfort level, i see open sourcing as the ideal next step.

but it's a long way to go.

**Comment by hh7843175** [comment]
@jeaubin yeah, it works for me, thanks man.

@siming85  I hope this great framework be open source, one day.  many people can work on it and develop/enhance its feature or functionality.
