### ISSUE TITLE
Is `vrf` a reserved key in `topology` in a testbed definition?

### ISSUE THREAD

**Issue by supertylerc** [CiscoTestAutomation/pyats#16]
I couldn't find documentation on the `vrf` key, but it looks like either pyATS or Genie want to do something special with it.  I was attempting to use it as a custom key.

A snippet of my testbed example topology:

```yaml
topology:                    
  spine1:                
    interfaces:              
      Ethernet1/1:       
        ipv4: 10.3.1.0/31    
        link: spine1-to-leaf1
        type: ethernet       
      Ethernet1/2:        
        ipv4: 10.4.1.0/31 
        link: spine1-to-leaf2
        type: ethernet        
      Ethernet1/3:    
        ipv4: 10.1.1.1/31
        link: border1-to-spine1
        type: ethernet       
      Ethernet1/4:           
        ipv4: 10.2.1.1/31
        link: border2-to-spine1
        type: ethernet    
      mgmt0:                 
        ipv4: 192.168.1.51    
        link: spine1-mgmt0     
        type: ethernet
        vrf: management
```

This results in the following error:

```
2018-12-17T13:43:07: %AETEST-ERROR: Caught exception during execution:                                             
2018-12-17T13:43:07: %AETEST-ERROR: Traceback (most recent call last):                                               
2018-12-17T13:43:07: %AETEST-ERROR:   File "/home/tyler/nfs/Projects/netdevops/pyats/example.py", line 40, in genie_init
2018-12-17T13:43:07: %AETEST-ERROR:     Genie.init(testbed=testbed)                                                                                        
2018-12-17T13:43:07: %AETEST-ERROR:   File "src/genie/conf/main.py", line 90, in genie.conf.main.Genie.init        
2018-12-17T13:43:07: %AETEST-ERROR:   File "src/genie/conf/utils/converter.py", line 60, in genie.conf.utils.converter.Converter.convert_tb
2018-12-17T13:43:07: %AETEST-ERROR:   File "src/genie/conf/utils/converter.py", line 164, in genie.conf.utils.converter.Converter.convert_device       
2018-12-17T13:43:07: %AETEST-ERROR:   File "src/genie/conf/utils/converter.py", line 231, in genie.conf.utils.converter.Converter.convert_interface
2018-12-17T13:43:07: %AETEST-ERROR:   File "src/genie/decorator.py", line 1168, in genie.decorator.managedattribute.__set__
2018-12-17T13:43:07: %AETEST-ERROR:   File "src/genie/decorator.py", line 781, in genie.decorator.managedattribute._default_setter                          
2018-12-17T13:43:07: %AETEST-ERROR:   File "src/genie/decorator.py", line 704, in genie.decorator.managedattribute._transform
2018-12-17T13:43:07: %AETEST-ERROR: ValueError: management: Not None. Not an instance of Vrf.         
```

I tried to find this in the pyATS documentation for the topology schema [here](https://pubhub.devnetcloud.com/media/pyats/docs/topology/schema.html), but I came up with nothing.  I could go code spelunking, but I'd also like to know if this is a bug, an intended feature, or if I'm just doing it wrong.

For now, I've worked around this by making the key `custom_vrf` and updating my code accordingly.

Thanks!

**Comment by karmoham** [comment]
Hi Tyler,

"vrf" is a reserved word within the "interface" object but it is not a reserved word to be used anywhere else in the testbed yaml file.

Hope that answered your question!

Thanks,
Karim

**Comment by supertylerc** [comment]
Great!  Thanks, @karmoham.  Any hint as to its use?  Is it simply reserved because of the object in Python, or does it have a use in the testbed YAML as well?

**Comment by karmoham** [comment]
Hi Tyler,

It is a managed attribute of the Genie "interface" object.

Source code is here https://github.com/CiscoTestAutomation/genielibs/blob/master/pkgs/conf-pkg/src/genie/libs/conf/interface/__init__.py#L178 

![image](https://user-images.githubusercontent.com/33664528/50122464-94cf3400-022a-11e9-8d71-30a2e9ec7870.png)

If you are interested in knowing how managed attributes work you can get the details from the following documentation https://developer.cisco.com/site/pyats/docs/packages/

Thanks,
Karim

**Comment by supertylerc** [comment]
Great.  Thank you!
