### ISSUE TITLE
getting error in a simple "show version" scenario

### ISSUE THREAD

**Issue by hh7843175** [CiscoTestAutomation/pyats#19]
Hi there, 

I think my problem is misunderstanding of pyATS, but I read and use sample codes which are available in pyATS repo.

the result of script is:

```
python test.py --testbed testbed.yaml
2019-01-10T17:17:42: %AETEST-INFO: Starting common setup
2019-01-10T17:17:42: %AETEST-INFO: Starting subsection check_topology
2019-01-10T17:17:42: %AETEST-INFO: The result of subsection check_topology is => PASSED
2019-01-10T17:17:42: %AETEST-INFO: Starting subsection establish_connections
2019-01-10T17:17:42: %AETEST-INFO: STEP 1: Connecting to ios-1
[2019-01-10 17:17:42,221] +++ ios-1 logfile /tmp/ios-1-default-20190110T171742221.log +++
[2019-01-10 17:17:42,221] +++ Unicon plugin ios +++
[2019-01-10 17:17:42,224] +++ connection to spawn: ssh -l admin 192.168.136.150, id: 140255415584080 +++
[2019-01-10 17:17:42,225] connection to ios-1
[2019-01-10 17:17:42,224] ssh -l admin 192.168.136.150
Password:
Password:

R2#

2019-01-10T17:18:53: %AETEST-INFO: STEP 1: Connecting to ios-1 - Errored
2019-01-10T17:18:53: %AETEST-ERROR: Caught exception during execution:
2019-01-10T17:18:53: %AETEST-ERROR: Traceback (most recent call last):
2019-01-10T17:18:53: %AETEST-ERROR:   File "src/unicon/statemachine/statemachine.py", line 683, in unicon.statemachine.statemachine.StateMachine.go_to
2019-01-10T17:18:53: %AETEST-ERROR:   File "src/unicon/statemachine/statetransition.py", line 479, in unicon.statemachine.statetransition.AnyStateTransition.do_transitions
2019-01-10T17:18:53: %AETEST-ERROR:   File "src/unicon/eal/dialogs.py", line 419, in unicon.eal.dialogs.Dialog.process
2019-01-10T17:18:53: %AETEST-ERROR:   File "src/unicon/eal/dialog_processor.py", line 659, in unicon.eal.dialog_processor.AlarmBasedDialogProcessor.process
2019-01-10T17:18:53: %AETEST-ERROR:   File "src/unicon/eal/dialog_processor.py", line 644, in unicon.eal.dialog_processor.AlarmBasedDialogProcessor.process
2019-01-10T17:18:53: %AETEST-ERROR:   File "src/unicon/eal/dialog_processor.py", line 546, in unicon.eal.dialog_processor.AlarmBasedDialogProcessor.expect_eval_statements
2019-01-10T17:18:53: %AETEST-ERROR:   File "src/unicon/eal/backend/pty_backend.py", line 131, in unicon.eal.backend.pty_backend.RawSpawn.read_update_buffer
2019-01-10T17:18:53: %AETEST-ERROR:   File "src/unicon/eal/backend/pty_backend.py", line 360, in unicon.eal.backend.pty_backend.RawPtySpawn.is_readable
2019-01-10T17:18:53: %AETEST-ERROR:   File "src/unicon/eal/backend/pty_backend.py", line 355, in unicon.eal.backend.pty_backend.RawPtySpawn.is_readable
2019-01-10T17:18:53: %AETEST-ERROR:   File "src/unicon/eal/dialog_processor.py", line 604, in unicon.eal.dialog_processor.AlarmBasedDialogProcessor.timeout_handler
2019-01-10T17:18:53: %AETEST-ERROR: TimeoutError: timeout occurred:
2019-01-10T17:18:53: %AETEST-ERROR:                               timeout value: 60
2019-01-10T17:18:53: %AETEST-ERROR:                               last_command: '123\r'
2019-01-10T17:18:53: %AETEST-ERROR:                              pattern: ['^.*?% (Bad passwords|Access denied|Authentication failed)', '^.*Login incorrect', '^.*([Uu]sername|[Ll]ogin): ?$', '^.*User Access Verification', '^.*[Pp]assword( for )?(\\S+)?: ?$', 'Escape character is .*\\n', '^.*RETURN to get started', 'Are you sure you want to continue connecting \\(yes/no\\)', '^.*(Connection refused|Connection reset by peer|Network is down|closed by remote host)', 'Received disconnect from .*:', 'Hit Enter to proceed:', '^(.*?)Press Ctrl\\+x to Exit the session', '^.*?% (Bad passwords|Access denied|Authentication failed)', '^.*([Uu]sername|[Ll]ogin): ?$', '^.*User Access Verification', '^.*[Pp]assword( for )?(\\S+)?: ?$', 'Password OK\\s*$', '^.*[Pp]assword( for )?(\\S+)?: ?$', 'rommon[\\s\\d]*>\\s?$', '^(.*?)(Router|Router-stby|Router-sdby|RouterRP|RouterRP-standby|ios-1-standby|ios-1-sdby|ios-1-stby|(S|s)witch|s(S|s)witch\\(standby\\)|Controller|ios|-Slot[0-9]+|ios-1)(\\(boot\\))*>\\s?$', '^(.*)\\(.*(con|cfg|ipsec-profile)\\S*\\)#\\s?$', '^(.*?)(Router|Router-stby|Router-sdby|RouterRP|RouterRP-standby|ios-1-standby|ios-1\\(standby\\)|ios-1-sdby|ios-1-stby|(S|s)witch|(S|s)witch\\(standby\\)|Controller|ios|-Slot[0-9]+|ios-1)(\\(boot\\))*#\\s?$', '^.*--\\s?[Mm]ore\\s?--.*', '^.*\\[confirm(\\(y/n\\))?\\]', '^.*\\[yes[/,][Nn][Oo]\\]\\s?:?$']
2019-01-10T17:18:53: %AETEST-ERROR:                              buffer:'\r\n\r\nR2#'
2019-01-10T17:18:53: %AETEST-ERROR:
2019-01-10T17:18:53: %AETEST-ERROR: The above exception was the direct cause of the following exception:
2019-01-10T17:18:53: %AETEST-ERROR:
2019-01-10T17:18:53: %AETEST-ERROR: Traceback (most recent call last):
2019-01-10T17:18:53: %AETEST-ERROR:   File "src/unicon/bases/connection.py", line 497, in unicon.bases.connection.Connection.connect
2019-01-10T17:18:53: %AETEST-ERROR:   File "src/unicon/bases/routers/connection_provider.py", line 146, in unicon.bases.routers.connection_provider.BaseSingleRpConnectionProvider.connect
2019-01-10T17:18:53: %AETEST-ERROR:   File "src/unicon/bases/routers/connection_provider.py", line 167, in unicon.bases.routers.connection_provider.BaseSingleRpConnectionProvider.establish_connection
2019-01-10T17:18:53: %AETEST-ERROR:   File "src/unicon/statemachine/statemachine.py", line 686, in unicon.statemachine.statemachine.StateMachine.go_to
2019-01-10T17:18:53: %AETEST-ERROR: unicon.core.errors.StateMachineError: Failed while bringing device to "any" state
2019-01-10T17:18:53: %AETEST-ERROR:
2019-01-10T17:18:53: %AETEST-ERROR: The above exception was the direct cause of the following exception:
2019-01-10T17:18:53: %AETEST-ERROR:
2019-01-10T17:18:53: %AETEST-ERROR: Traceback (most recent call last):
2019-01-10T17:18:53: %AETEST-ERROR:   File "test.py", line 27, in establish_connections
2019-01-10T17:18:53: %AETEST-ERROR:     ios1.connect()
2019-01-10T17:18:53: %AETEST-ERROR:   File "src/pyats/connections/manager.py", line 283, in pyats.connections.manager.ConnectionManager.connect
2019-01-10T17:18:53: %AETEST-ERROR:   File "src/unicon/bases/connection.py", line 501, in unicon.bases.connection.Connection.connect
2019-01-10T17:18:53: %AETEST-ERROR: unicon.core.errors.ConnectionError: failed to connect to ios-1
2019-01-10T17:18:53: %AETEST-INFO: +----------------------------------------------------------+
2019-01-10T17:18:53: %AETEST-INFO: |                       STEPS Report                       |
2019-01-10T17:18:53: %AETEST-INFO: +----------------------------------------------------------+
2019-01-10T17:18:53: %AETEST-INFO: STEP 1 - Connecting to ios-1                         Errored
2019-01-10T17:18:53: %AETEST-INFO: ------------------------------------------------------------
2019-01-10T17:18:53: %AETEST-INFO: The result of subsection establish_connections is => ERRORED
2019-01-10T17:18:53: %AETEST-INFO: The result of common setup is => ERRORED
2019-01-10T17:18:53: %AETEST-INFO: Starting testcase PingTestcase
2019-01-10T17:18:53: %AETEST-INFO: Blocking PingTestcase because common_setup did not pass.
2019-01-10T17:18:53: %AETEST-INFO: The result of testcase PingTestcase is => BLOCKED
2019-01-10T17:18:53: %AETEST-INFO: Starting common cleanup
2019-01-10T17:18:53: %AETEST-INFO: Starting subsection disconnect
2019-01-10T17:18:53: %AETEST-INFO: STEP 1: Disconnecting from ios-1
2019-01-10T17:19:05: %AETEST-INFO: STEP 1: Disconnecting from ios-1 - Passed
2019-01-10T17:19:05: %AETEST-INFO: +----------------------------------------------------------+
2019-01-10T17:19:05: %AETEST-INFO: |                       STEPS Report                       |
2019-01-10T17:19:05: %AETEST-INFO: +----------------------------------------------------------+
2019-01-10T17:19:05: %AETEST-INFO: STEP 1 - Disconnecting from ios-1                     Passed
2019-01-10T17:19:05: %AETEST-INFO: ------------------------------------------------------------
2019-01-10T17:19:05: %AETEST-INFO: The result of subsection disconnect is => PASSED
2019-01-10T17:19:05: %AETEST-INFO: The result of common cleanup is => PASSED
2019-01-10T17:19:05: %AETEST-INFO: +------------------------------------------------------------------------------+
2019-01-10T17:19:05: %AETEST-INFO: |                               Detailed Results                               |
2019-01-10T17:19:05: %AETEST-INFO: +------------------------------------------------------------------------------+
2019-01-10T17:19:05: %AETEST-INFO:  SECTIONS/TESTCASES                                                      RESULT
2019-01-10T17:19:05: %AETEST-INFO: --------------------------------------------------------------------------------
2019-01-10T17:19:05: %AETEST-INFO: .
2019-01-10T17:19:05: %AETEST-INFO: |-- common_setup                                                        ERRORED
2019-01-10T17:19:05: %AETEST-INFO: |   |-- check_topology                                                   PASSED
2019-01-10T17:19:05: %AETEST-INFO: |   `-- establish_connections                                           ERRORED
2019-01-10T17:19:05: %AETEST-INFO: |       `-- Step 1: Connecting to ios-1                                 ERRORED
2019-01-10T17:19:05: %AETEST-INFO: |-- PingTestcase                                                        BLOCKED
2019-01-10T17:19:05: %AETEST-INFO: `-- common_cleanup                                                       PASSED
2019-01-10T17:19:05: %AETEST-INFO:     `-- disconnect                                                       PASSED
2019-01-10T17:19:05: %AETEST-INFO:         `-- Step 1: Disconnecting from ios-1                             PASSED
2019-01-10T17:19:05: %AETEST-INFO: +------------------------------------------------------------------------------+
2019-01-10T17:19:05: %AETEST-INFO: |                                   Summary                                    |
2019-01-10T17:19:05: %AETEST-INFO: +------------------------------------------------------------------------------+
2019-01-10T17:19:05: %AETEST-INFO:  Number of ABORTED                                                            0
2019-01-10T17:19:05: %AETEST-INFO:  Number of BLOCKED                                                            1
2019-01-10T17:19:05: %AETEST-INFO:  Number of ERRORED                                                            1
2019-01-10T17:19:05: %AETEST-INFO:  Number of FAILED                                                             0
2019-01-10T17:19:05: %AETEST-INFO:  Number of PASSED                                                             1
2019-01-10T17:19:05: %AETEST-INFO:  Number of PASSX                                                              0
2019-01-10T17:19:05: %AETEST-INFO:  Number of SKIPPED                                                            0
2019-01-10T17:19:05: %AETEST-INFO: --------------------------------------------------------------------------------

```

I just want to write a simple test for one router, read the out put of `show version` command and print/process it, like a `Hello World!` sample code.

Thanks in advance.

[test.zip](https://github.com/CiscoTestAutomation/pyats/files/2745579/test.zip)

**Comment by jeaubin** [comment]
The Device name in the yaml file must match the hostname of your device.

`devices:
    ios-1:       <----  should be R2
        os: ios
        type: ios
        connections:
            vty:
                protocol: ssh
                ip: 192.168.136.150
`

**Comment by hh7843175** [comment]
@jeaubin Thank you so much, it works but I've got new error:

```
2019-01-10T17:38:45: %AETEST-ERROR: Caught exception during execution:
2019-01-10T17:38:45: %AETEST-ERROR: ValueError: no parameter 'device' in scope of '<bound method ShowVersionTestcase.show_version of <class 'ShowVersionTestcase' uid='ShowVersionTestcase'>>'
```

**Comment by jeaubin** [comment]
This seems like the device has not been added to the [parameters](https://pubhub.devnetcloud.com/media/pyats/docs/aetest/parameters.html).

In your common setup, you probably have something similar;

```
device = testbed.devices['R2']
```

And then later you have

```
class ShowVersionTestcase(aetest.Testcase):
    """This is description for my testcase one"""
    @aetest.setup
    def show_version(self, device):
```

This device argument is a parameters that needed to be added in a previous section (Common setup makes to most sense in most case). Here how to do it. 

```
def connect(self, testscript, testbed):
    """ common setup subsection: connecting devices """

    # Grab the device object of the uut device with that name
    device = testbed.devices['R2']

    # Save it in testscript parmaeters to be able to use it from other
    # test sections
    testscript.parameters['device'] = device      <-- This line will do it.
```

Take a look at the attached file and make sure to read the parameters documentation to get a better idea how it all works. 

[script_example.py.zip](https://github.com/CiscoTestAutomation/pyats/files/2745691/script_example.py.zip)
