### ISSUE TITLE
Error for "n*Nd" route types for IOSXE when using learn routing.

### ISSUE THREAD

**Issue by fiblund** [CiscoTestAutomation/pyats#190]
Hi :) 

First of all - Fantastic tool! :)

I have tested using pyATS to learn routing from IOSXE routers in SD-WAN mode, and I get an error for routes with the type "n*Nd".

n*Nd is a NAT default route:
n - NAT
Nd - NAT DIA
* - candidate default

Here is the traceback
(venv) ➜  pyats git:(main) ✗ more pre_change/routing_iosxe_DEBEREVOR01_exception.txt 
Issue while building the feature

Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 365, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/Users/frederikfibiger-lundberg/projects/pyats/venv/lib/python3.9/site-packages/genie/libs/ops/routing/iosxe/routing.py", line 143, in learn
    self.make(final_call=True)
  File "/Users/frederikfibiger-lundberg/projects/pyats/venv/lib/python3.9/site-packages/genie/ops/base/base.py", line 103, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 315, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 427, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 308, in genie.metaparser._metaparser.MetaParser.parse
  File "/Users/frederikfibiger-lundberg/projects/pyats/venv/lib/python3.9/site-packages/genie/libs/parser/iosxe/show_routing.py", line 50, in cli
    return parser.parse(output=out)
  File "src/genie/metaparser/_metaparser.py", line 308, in genie.metaparser._metaparser.MetaParser.parse
  File "/Users/frederikfibiger-lundberg/projects/pyats/venv/lib/python3.9/site-packages/genie/libs/parser/iosxe/show_routing.py", line 439, in cli
    route_dict['source_protocol'] = source_protocol
UnboundLocalError: local variable 'source_protocol' referenced before assignment

I have managed to fix the issue locally by adding the following code:
229: # added to support "n*Nd" route types, which are used in Cisco SD-WAN for NAT DIA routes
230: source_protocol_dict['nat_dia'] = ['n', 'Nd']

<img width="947" alt="image" src="https://user-images.githubusercontent.com/37215596/202662362-96ae059b-a59d-4a83-b4e4-b19351ba1bf6.png">

**Comment by Taarini** [comment]
Hi 

Can you please share the os, platform and device output for the above. It would be helpful in debugging

**Comment by Taarini** [comment]
Hi

Yes that fixes the problem.

Can you please contribute to the genieparser community.
All you need to do is create a PR in genieparser community and add the above changes along with the expected output and parsed output as unit test to justify your changes. 

Below is the link to guide you through parser contribution,
https://pubhub.devnetcloud.com/media/pyats-development-guide/docs/writeparser/writeparser.html

**Comment by Taarini** [comment]
Yes all good approved the PR
