### ISSUE TITLE
Could not find parser for show isis adjacency under ('junos', 'MX', None)

### ISSUE THREAD

**Issue by HATmess** [CiscoTestAutomation/pyats#202]
Hi team,

As pyats is considered as open and multivendor seems like most commands are not supported for other vendors like junos. 

please your support.

**Comment by HATmess** [comment]
here the outputs:

bgp is not yet developed for device MX480-R06-01

Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 315, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "src/genie/ops/utils.py", line 167, in genie.ops.utils.get_ops
KeyError: 'package'


Traceback (most recent call last):
  File "/mnt/c/Users/user/PycharmProjects/pats_space/main.py", line 14, in <module>
    show_interface = dev.parse('show isis adjacency')
  File "src/genie/conf/base/device.py", line 529, in genie.conf.base.device.Device.parse
  File "/usr/local/lib/python3.10/dist-packages/genie/libs/parser/utils/common.py", line 166, in get_parser
    raise ParserNotFound(command, lookup._tokens)
genie.libs.parser.utils.common.ParserNotFound: Could not find parser for show isis adjacency under ('junos', 'MX', None)
root@ALG-330009-LT:/mnt/c/Users/user/PycharmProjects/pats_space# pyats learn bgp --testbed-file mytest.yaml --output today

Learning '['bgp']' on devices '['MX480-R06-01']'
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.05it/s]
+==============================================================================+
| Genie Learn Summary for device MX480-R06-01                                  |
+==============================================================================+
|  Connected to MX480-R06-01                                                   |
|  -   Log: today/connection_MX480-R06-01.txt                                  |
|------------------------------------------------------------------------------|
|  Could not learn feature 'bgp'                                               |
|  -  Exception:      today/bgp_junos_MX480-R06-01_exception.txt               |
|  -  Feature not yet developed for this os                                    |
|==============================================================================|

**Comment by Taarini** [comment]
Hi

Thanks for reporting the issue. Since genieparser is community driven. Requesting you to contribute to the library with the potential fix to help resolve the issue. Please let me know of any help you need to create a PR with the fix

**Comment by Taarini** [comment]
Hi

Please let me know whether you're planning to contribute to the community. If not I can add this to our backlog and let you know once it is released.

**Comment by Taarini** [comment]
Hi

Please provide an update so that we can plan accordingly
