### ISSUE TITLE
AttributeError: 'ProcessorDecorator' object has no attribute 'source'

### ISSUE THREAD

**Issue by jtirodka** [CiscoTestAutomation/pyats#205]
Hi I am trying to run pyats automation and facing this error 

2023-02-28T16:39:41: %AETEST-INFO: +------------------------------------------------------------------------------+
2023-02-28T16:39:41: %AETEST-INFO: |                            Starting common setup                             |
2023-02-28T16:39:41: %AETEST-INFO: +------------------------------------------------------------------------------+
Caught an exception while executing common setup:
Traceback (most recent call last):
  File "/ws/jtirodka-sjc/pyats_new/lib/python3.6/site-packages/pyats/aetest/discovery.py", line 346, in __iter__
    for section in self.discover():
  File "/ws/jtirodka-sjc/pyats_new/lib/python3.6/site-packages/pyats/aetest/discovery.py", line 421, in discover
    return self.order(*subsections)
  File "/ws/jtirodka-sjc/pyats_new/lib/python3.6/site-packages/pyats/aetest/discovery.py", line 424, in order
    return sorted(subsections, key = lambda section: section.source)
  File "/ws/jtirodka-sjc/pyats_new/lib/python3.6/site-packages/pyats/aetest/discovery.py", line 424, in <lambda>
    return sorted(subsections, key = lambda section: section.source)
AttributeError: 'ProcessorDecorator' object has no attribute 'source'

Here are my pyats package details from env :
(pyats_alt2) bash-4.2$ pip3 freeze | grep ats
ats==20.7
ats.aereport==20.7
ats.aetest==20.7
ats.async==20.7
ats.cisco==20.7.1
ats.connections==20.7
ats.datastructures==20.7
ats.easypy==20.7
ats.kleenex==20.7
ats.log==20.7
ats.reporter==20.7
ats.results==20.7
ats.robot==20.7
ats.tcl==20.7
ats.topology==20.7
ats.utils==20.7
pyats.contrib==20.7

**Comment by kameswararaot** [comment]
Hi jtirodka, 
Please let me know you are looking for the support for this issue?

Please make sure to add the logs / pyats version / package list.

**Comment by kameswararaot** [comment]
Hi jtirodka,
if you are looking for support, Please make sure to add the logs / pyats version / package list.

**Comment by kameswararaot** [comment]
Hi jtirodka,
if you are looking for support, Please make sure to add the logs / pyats version / package list.

**Comment by jtirodka** [comment]
Hi,

I did a reinstall of the full pyats version and that resolved the issue for
me.

Thanks,
Janhavi

**Comment by kameswararaot** [comment]
Hi Janhavi,

Thanks for the update.
