### ISSUE TITLE
ModuleNotFoundError: No module named 'genie.webdriver' in pyATS version 24.7

### ISSUE THREAD

**Issue by rirajak** [CiscoTestAutomation/pyats#246]
I caught up with an error ModuleNotFoundError: No module named 'genie.webdriver'. In pyATS version 24.7.

### ERROR MESSAGE

Caught error in plugin 'TestbedPlugin':
 
 Traceback (most recent call last):
   File "/root/pyATS/lib/python3.11/site-packages/pyats/utils/import_utils/misc.py", line 52, in import_from_name
     return getattr(import_module(module or name), clsname)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/auto/pysw/cel8x/python64/3.11.2/lib/python3.11/importlib/__init__.py", line 126, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
 ModuleNotFoundError: No module named 'genie.webdriver'
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/root/pyATS/lib/python3.11/site-packages/pyats/utils/schemaengine.py", line 623, in validate
     return self.schema(data)
            ^^^^^^^^^^^^^^^^^
   File "/root/pyATS/lib/python3.11/site-packages/pyats/utils/import_utils/misc.py", line 55, in import_from_name
     raise ImportError("Failed to import '%s'" % name) from e
 ImportError: Failed to import 'genie.webdriver.connectors.WebDriverConnector'
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/root/pyATS/lib/python3.11/site-packages/pyats/easypy/plugins/testbed.py", line 77, in pre_job
     self.runtime.job.testbed = loader.load(testbed_file)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/pyATS/lib/python3.11/site-packages/pyats/topology/loader/__init__.py", line 44, in load
     return TestbedFileLoader(**init_kwargs).load(loadable, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/pyATS/lib/python3.11/site-packages/pyats/utils/yaml/loader.py", line 176, in load
     content = schemaengine.Schema(self.schema).validate(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/pyATS/lib/python3.11/site-packages/pyats/utils/schemaengine.py", line 295, in validate
     matchValue = Schema(sv, path).validate(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/pyATS/lib/python3.11/site-packages/pyats/utils/schemaengine.py", line 366, in validate
     matchValue = Schema(sv, path).validate(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/pyATS/lib/python3.11/site-packages/pyats/utils/schemaengine.py", line 295, in validate
     matchValue = Schema(sv, path).validate(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/pyATS/lib/python3.11/site-packages/pyats/utils/schemaengine.py", line 366, in validate
     matchValue = Schema(sv, path).validate(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/pyATS/lib/python3.11/site-packages/pyats/utils/schemaengine.py", line 366, in validate
     matchValue = Schema(sv, path).validate(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/pyATS/lib/python3.11/site-packages/pyats/utils/schemaengine.py", line 251, in validate
     return self.schema.validate(
            ^^^^^^^^^^^^^^^^^^^^^
   File "/root/pyATS/lib/python3.11/site-packages/pyats/utils/schemaengine.py", line 636, in validate
     raise SchemaError(msg, locations=err_locs) from x
 pyats.utils.exceptions.SchemaError: import_from_name('genie.webdriver.connectors.WebDriverConnector') raised ImportError("Failed to import 'genie.webdriver.connectors.WebDriverConnector'")
 
### Installed Packages

ats 24.7
ats.aereport 24.7
ats.aetest 24.7
ats.async 24.7
ats.cisco 24.7
ats.connections 24.7
ats.datastructures 24.7
ats.easypy 24.7
ats.kleenex 24.7
ats.log 24.7
ats.reporter 24.7
ats.results 24.7
ats.robot 24.7
ats.tcl 24.7
ats.topology 24.7
ats.utils 24.7
genie 24.7
genie.libs.cisco 24.7
genie.libs.clean 24.7
genie.libs.conf 24.7
genie.libs.filetransferutils 24.7
genie.libs.health 24.7
genie.libs.ops 24.7
genie.libs.parser 24.7
genie.libs.robot 24.7
genie.libs.sdk 24.7
genie.telemetry 24.7
genie.trafficgen 24.7
genie.webdriver 24.7
pyats.contrib 24.7
unicon 24.7
unicon.internal.plugins 24.7
unicon.plugins 24.7

 [TaaS log](https://ngdevx.cisco.com/services/taas/results/92a5bb99-230c-4244-a0aa-18ea06f886c9)

**Comment by Harishv01** [comment]
Hi, Can you please let me know from which version you are facing this issue? If it worked in any previous versions, please share the passed log to debug the issue. Thank you.

**Comment by Harishv01** [comment]
We have found the solution, and it will be available soon in the pyats 23.8 release.
