### ISSUE TITLE
Example pyats test case fails to import ats.aetest

### ISSUE THREAD

**Issue by zachwhaley** [CiscoTestAutomation/pyats#3]
Using the latest pyats version (4.1) and running the pyats example code, my test case said it was unable to import ats.aetest :open_mouth: 

```console
$ pip list | grep pyats
pyats (4.1.0)
pyats.aereport (4.1.0)
pyats.aetest (4.1.1)
pyats.async (4.1.0)
pyats.connections (4.1.0)
pyats.datastructures (4.1.0)
pyats.easypy (4.1.0)
pyats.examples (4.1.0)
pyats.kleenex (4.1.0)
pyats.log (4.1.0)
pyats.results (4.1.0)
pyats.tcl (4.1.0)
pyats.templates (4.1.0)
pyats.topology (4.1.0)
pyats.utils (4.1.0)
$ python --version
Python 3.4.7
$ python basic/basic_example_script.py 
Traceback (most recent call last):
  File "basic/basic_example_script.py", line 19, in <module>
    from ats import aetest
  File "/home/zacharyw/.pyenv/versions/3.4.7/lib/python3.4/site-packages/ats/aetest/__init__.py", line 32, in <module>
    from .main import main
ImportError: /home/zacharyw/.pyenv/versions/3.4.7/lib/python3.4/site-packages/ats/aetest/main.cpython-34m.so: wrong ELF class: ELFCLASS32
```

**Comment by siming85** [comment]
hi - is this on a mac, or on linux?

32bit, or 64bit python interpreter?

**Comment by siming85** [comment]
found a bug with aetest v4.1.1 - built in in 32-bit instead of default 64.

updated with v4.1.2.

also fixed a few bugs along the way - please update the following:
```
bash$ pip install --upgrade pyats.aetest pyats.easypy pyats.topology pyats.utils
```
