### ISSUE TITLE
Need Help. Timeout after 1 hour

### ISSUE THREAD

**Issue by urskog84** [CiscoTestAutomation/pyats#31]
I am running a rather big test, on approximately 250 access switches / devices.

The collection process of gathering the test data takes more the 1 hour to finish .
So the test is ERRORED. and i only 2/3 of the devices have data collected for the next test case.
```
+------------------------------------------------------------------------------+
|             Gahter parst data from stjipswi019 | show interfaces             |
+------------------------------------------------------------------------------+
+++ stjipswi019: executing command 'show interfaces' +++
Connection to 10.144.56.29 closed by remote host.
Connection to 10.144.56.29 closed.
show interfaces
 Caught an exception while executing TestSection 'collect_interface_data':
 Traceback (most recent call last):
   File "src/unicon/eal/backend/pty_backend.py", line 452, in unicon.eal.backend.pty_backend.RawPtySpawn._read
 OSError: [Errno 5] Input/output error
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/pyats/lib/python3.6/site-packages/unicon/plugins/generic/service_implementation.py", line 703, in call_service
:     context=con.context
:   File "src/unicon/eal/dialogs.py", line 430, in unicon.eal.dialogs.Dialog.process
:   File "src/unicon/eal/dialog_processor.py", line 295, in unicon.eal.dialog_processor.SimpleDialogProcessor.process
:   File "src/unicon/eal/dialog_processor.py", line 217, in unicon.eal.dialog_processor.SimpleDialogProcessor.expect_eval_statements
:   File "src/unicon/eal/backend/pty_backend.py", line 133, in unicon.eal.backend.pty_backend.RawSpawn.read_update_buffer
:   File "src/unicon/eal/backend/pty_backend.py", line 118, in unicon.eal.backend.pty_backend.RawSpawn.read
:   File "src/unicon/eal/backend/pty_backend.py", line 455, in unicon.eal.backend.pty_backend.RawPtySpawn._read
: unicon.core.errors.EOF: ('Unable to read. Connection closed or not available', OSError(5, 'Input/output error'))
: 
: The above exception was the direct cause of the following exception:
: 
: Traceback (most recent call last):
:   File "src/genie/metaparser/_metaparser.py", line 271, in genie.metaparser._metaparser.MetaParser.parse
:   File "/pyats/lib/python3.6/site-packages/genie/libs/parser/iosxe/show_interface.py", line 203, in cli
:     out = self.device.execute(cmd)
:   File "src/unicon/bases/routers/services.py", line 190, in unicon.bases.routers.services.BaseService.__call__
:   File "/pyats/lib/python3.6/site-packages/unicon/plugins/generic/service_implementation.py", line 712, in call_service
:     raise SubCommandFailure("Command execution failed", err) from err
: unicon.core.errors.SubCommandFailure: ('Command execution failed', EOF('Unable to read. Connection closed or not available', OSError(5, 'Input/output error')))
: 
: The above exception was the direct cause of the following exception:
: 
: Traceback (most recent call last):
:   File "/pyats/test_interface_config.py", line 79, in collect_interface_data
:     interfaces = device.parse("show interfaces")
:   File "src/genie/conf/base/device.py", line 529, in genie.conf.base.device.Device.parse
:   File "src/genie/metaparser/_metaparser.py", line 274, in genie.metaparser._metaparser.MetaParser.parse
: genie.metaparser.util.exceptions.InvalidCommandError: Invalid command has been executed
  The result of section collect_interface_data is => ERRORED
```

how can i keep the connection open to the device?
or can i reconnect automatic if i lose the connection?

**Comment by difuhu** [comment]
Hi Petter,

It is probably because the connection got timeout and disconnected by remote.
You can patch init_config_commands in testbed.yaml to make the connection never timeout. init_config_commands will be configured at the stage of device.connect()
Following are the example and you may need to adjust the command according to your platform and configuration, eg 'line vty 1' or any other different commands.
```
    connections:
      vty:
        protocol: telnet
        ip: 10.144.56.29
        init_config_commands: ['no logging console', 'line vty 0', 'exec-timeout 0']

```

**Comment by urskog84** [comment]
Sound like a good solution, lets try it out!!

**Comment by urskog84** [comment]
Thanks @difuhu. I hade to modify the connection YAML slitly, do to our Cisco Prime installation stealing "vty 0" ssh session

```
stjipswi019 #show ssh
Connection Version Mode Encryption  Hmac         State                 Username
0          2.0     IN   aes128-ctr  hmac-sha1-96 Session started       ciscoprime_user
0          2.0     OUT  aes128-ctr  hmac-sha1-96 Session started       ciscoprime_user
1          2.0     IN   aes128-ctr  hmac-sha1    Session started       myuser
1          2.0     OUT  aes128-ctr  hmac-sha1    Session started       myuser
%No SSHv1 server connections running.
```
I have now modify init_config_commands list to this ->
```
    connections:
      vty:
        protocol: telnet
        ip: 10.144.56.29
        init_config_commands: ['no logging console', 'line vty 0 4', 'exec-timeout 0']
```

It works grate now!
many thanks to pyats team
