### ISSUE TITLE
Unable to run easily on Mac 10.13.6 (17G65)

### ISSUE THREAD

**Issue by extsoft** [CiscoTestAutomation/pyats#4]
I have configured a simple test and a job to run this test. When I run it with `easypy`, I have `socket.gaierror: [Errno 8] nodename nor servname provided, or not known` error and the test is not executed.

Environment setup:
- python `3.6.5`
- pyats `4.1.0`

Pip log:
```
pip list
Package              Version  
-------------------- ---------
asynctest            0.12.2   
blinker              1.4      
certifi              2018.8.13
chardet              3.0.4    
graphviz             0.9      
httplib2             0.11.3   
idna                 2.7      
Jinja2               2.10     
junit-xml            1.8      
MarkupSafe           1.0      
pip                  18.0     
psutil               5.4.7    
pyats                4.1.0    
pyats.aereport       4.1.0    
pyats.aetest         4.1.3    
pyats.async          4.1.0    
pyats.connections    4.1.0    
pyats.datastructures 4.1.0    
pyats.easypy         4.1.10   
pyats.examples       4.1.0    
pyats.kleenex        4.1.0    
pyats.log            4.1.0    
pyats.results        4.1.0    
pyats.tcl            4.1.1    
pyats.templates      4.1.0    
pyats.topology       4.1.2    
pyats.utils          4.1.4    
PyYAML               3.13     
requests             2.19.1   
setproctitle         1.1.10   
setuptools           40.2.0   
six                  1.11.0   
unicon               3.2.0    
urllib3              1.23     
wheel                0.31.1   
```

The tests: 
```python
# smoke_test.py
from ats import aetest

from ats.aetest import test


class Smoke(aetest.Testcase):
    @test
    def test_one(self):
        print('Smoke test is passed')

```
```python
# smore_job.py
import os
from ats import easypy


def main():
    script_path = os.path.dirname(os.path.abspath(__file__))
    testscript = os.path.join(script_path, 'smoke_test.py')
    easypy.run(testscript=testscript)

```
Execution log: 
```bash
$ easypy smoke_job.py 
Process ForkProcess-2:
Traceback (most recent call last):
  File "/python/3.6.5/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/python/3.6.5/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "src/ats/aereport/toplevel/decorators.py", line 43, in ats.aereport.toplevel.decorators.log_it.inner
  File "src/ats/aereport/toplevel/decorators.py", line 36, in ats.aereport.toplevel.decorators.log_it.inner
  File "src/ats/aereport/aerunner.py", line 5336, in ats.aereport.aerunner.AERunner.run_server
  File "src/ats/aereport/aerunner.py", line 5933, in ats.aereport.aerunner.OrphanFreeSimpleXMLRPCServer.__init__
  File "/python/3.6.5/lib/python3.6/xmlrpc/server.py", line 598, in __init__
    socketserver.TCPServer.__init__(self, addr, requestHandler, bind_and_activate)
  File "/python/3.6.5/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/python/3.6.5/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
2018-08-22T12:44:49: %EASYPY-ERROR: !!! an unhandled exception has interrupted execution !!!
2018-08-22T12:44:49: %EASYPY-ERROR: 
2018-08-22T12:44:49: %EASYPY-ERROR: This may be caused by:
2018-08-22T12:44:49: %EASYPY-ERROR:     - keyboard interrupts (ctrl+c)
2018-08-22T12:44:49: %EASYPY-ERROR:     - job file issues
2018-08-22T12:44:49: %EASYPY-ERROR:     - unexpected exceptions from your plugins
2018-08-22T12:44:49: %EASYPY-ERROR: 
2018-08-22T12:44:49: %EASYPY-ERROR: As a consequence:
2018-08-22T12:44:49: %EASYPY-ERROR:     - execution crashed and the environment may not be cleaned up
2018-08-22T12:44:49: %EASYPY-ERROR:     - TRADE/TIMS uploading will likely not occur
2018-08-22T12:44:49: %EASYPY-ERROR: 
2018-08-22T12:44:49: %EASYPY-ERROR: Please investigate the traceback below before raising issue to pyats-support.
2018-08-22T12:44:49: %EASYPY-ERROR: 
2018-08-22T12:44:49: %EASYPY-ERROR: --------------------------------------------------------------------------------
2018-08-22T12:44:49: %EASYPY-ERROR: 
2018-08-22T12:44:49: %EASYPY-ERROR: pyATS Instance   : /python/3.6.5/envs/pyats
2018-08-22T12:44:49: %EASYPY-ERROR: Python Version   : cpython-3.6.5 (64bit)
2018-08-22T12:44:49: %EASYPY-ERROR: CLI Arguments    : /python/pyats/bin/easypy smoke_job.py
2018-08-22T12:44:49: %EASYPY-ERROR: User             : user
2018-08-22T12:44:49: %EASYPY-ERROR: Host Server      : mac
2018-08-22T12:44:49: %EASYPY-ERROR: Host OS Version  : Mac OSX 10.13.6 (x86_64)
2018-08-22T12:44:49: %EASYPY-ERROR: 
2018-08-22T12:44:49: %EASYPY-ERROR: Traceback (most recent call last):
2018-08-22T12:44:49: %EASYPY-ERROR:   File "src/ats/easypy/reporter/ae.py", line 114, in ats.easypy.reporter.ae.AEReporter.start
2018-08-22T12:44:49: %EASYPY-ERROR:   File "src/ats/aereport/aerunner.py", line 5256, in ats.aereport.aerunner.AERunner.start_server
2018-08-22T12:44:49: %EASYPY-ERROR: ats.aereport.exceptions.aereport_errors.ServerNotStarted: 'Server could not be started. AEReport server will not be started'
2018-08-22T12:44:49: %EASYPY-INFO: No SMTP server information configured, ignoring sending notification email.
2018-08-22T12:44:49: %EASYPY-INFO: Done!
```

**Comment by siming85** [comment]
this is a common issue with Python XMLRPCServer (which we use in the reporting).

The fix is to add your hostname behind ``127.0.0.1`` in ``/etc/hosts`` file

Eg from this
```text
127.0.0.1	localhost
```

to this
``` text
127.0.0.1	localhost my-mbp
```

**Comment by extsoft** [comment]
@siming85 is it possible to add this somewhere in the documentation?

**Comment by siming85** [comment]
it's the first thing that comes up with that exception...

it's not exactly pyATS specific:

https://stackoverflow.com/questions/39970606/gaierror-errno-8-nodename-nor-servname-provided-or-not-known-with-macos-sie

**Comment by extsoft** [comment]
@siming85 got it.
