### ISSUE TITLE
pdb.set_trace() throws exception when "pyats run job ..."

### ISSUE THREAD

**Issue by sshuguan** [CiscoTestAutomation/pyats#43]
**pdb.set_trace()**  in my_tests.py file results in exception when it is invoked by **pyats run job my_job.py --testbed-file ./my_tb.yaml**.

my_job.py:
```
  import os
  mypath = os.path.dirname(__file__)
  def main(runtime):
     script = os.path.join(mypath, 'my_tests.py')
     runtime.tasks.run(script)
```

my_tests.py:
```
from pyats import aetest
from genie.testbed import load
class CommonSetup(aetest.CommonSetup):
    @aetest.subsection
    def connect_tb_devices(self, testbed):
        self.parent.parameters['testbed'] = testbed = load(testbed)
        **pdb.set_trace()**

        # connect testbed devices
        for dev in testbed.devices.values():
            dev.connect()
            dev.mdcli_execute("environment more false")
```
Exception:
```
-> for dev in testbed.devices.values():
(Pdb) 
2020-03-11T09:44:45: %AETEST-ERROR: Caught an exception while executing subsection connect_tb_devices:
2020-03-11T09:44:45: %AETEST-ERROR: Traceback (most recent call last):
2020-03-11T09:44:45: %AETEST-ERROR:   File "/home/sshanggu/bell.ca/my_tests.py", line 37, in connect_tb_devices
2020-03-11T09:44:45: %AETEST-ERROR:     for dev in testbed.devices.values():
2020-03-11T09:44:45: %AETEST-ERROR:   File "/home/sshanggu/bell.ca/my_tests.py", line 37, in connect_tb_devices
2020-03-11T09:44:45: %AETEST-ERROR:     for dev in testbed.devices.values():
2020-03-11T09:44:45: %AETEST-ERROR:   File "/usr/local/lib/python3.7/bdb.py", line 88, in trace_dispatch
2020-03-11T09:44:45: %AETEST-ERROR:     return self.dispatch_line(frame)
2020-03-11T09:44:45: %AETEST-ERROR:   File "/usr/local/lib/python3.7/bdb.py", line 113, in dispatch_line
2020-03-11T09:44:45: %AETEST-ERROR:     if self.quitting: raise BdbQuit
2020-03-11T09:44:45: %AETEST-ERROR: bdb.BdbQuit
2020-03-11T09:44:45: %AETEST-INFO: The result of subsection connect_tb_devices is => ERRORED
2020-03-11T09:44:45: %AETEST-INFO: The result of common setup is => ERRORED
```

**Comment by simingy** [comment]
hey, use --pdb from command line to pyats run job.
this is due to tasks being run as a sub process, and python's multiprocessing bootstrap closes stdin on subprocesses, causing this weird error.

our --pdb argument just opens it again

**Comment by sshuguan** [comment]
Case closed. Thanks. Sam
