### ISSUE TITLE
pyATS offline install via pip install 

### ISSUE THREAD

**Issue by network-shark** [CiscoTestAutomation/pyats#44]
I'm trying to install pyATS which does not have internet accesss. I hope a have all files need to install pyATS. I used the pip download function .Created a req.txt and try to install it via pip install 

```
pip install --no-cache-dir --no-index --find-links . -r req_pyATS.txt
```
req_pyATS.txt
```
aiohttp==3.6.2                                                         
async-timeout==3.0.1                                                   
attrs==19.3.0                                                          
certifi==2019.11.28                                                    
chardet==3.0.4                                                         
dill==0.3.1.1                                                          
distro==1.4.0                                                          
idna==2.9                                                              
Jinja2==2.11.1                                                         
junit-xml==1.9                                                         
MarkupSafe==1.1.1                                                      
multidict==4.7.5                                                       
pathspec==0.7.0                                                        
psutil==5.7.0                                                          
PyYAML==5.3.1                                                          
requests==2.23.0                                                       
six==1.14.0                                                            
unicon==20.2                                                           
unicon.plugins==20.2                                                   
urllib3==1.25.8                                                        
yamllint==1.21.0                                                       
yarl==1.4.2                                                            
pyats==20.2.1                                                          
pyats.aereport==20.2                                                   
pyats.aetest==20.2                                                     
pyats.async==20.2                                                      
pyats.connections==20.2                                                
pyats.datastructures==20.2                                             
pyats.easypy==20.2                                                     
pyats.kleenex==20.2                                                    
pyats.log==20.2                                                        
pyats.reporter==20.2.2                                                 
pyats.results==20.2                                                    
pyats.tcl==20.2                                                        
pyats.topology==20.2                                                   
pyats.utils==20.2                                                      
```

```
Looking in links: .
Requirement already satisfied: aiohttp==3.6.2 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from -r req_pyATS.txt (line 1)) (3.6.2)
Requirement already satisfied: async-timeout==3.0.1 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from -r req_pyATS.txt (line 2)) (3.0.1)
Requirement already satisfied: attrs==19.3.0 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from -r req_pyATS.txt (line 3)) (19.3.0)
Requirement already satisfied: certifi==2019.11.28 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from -r req_pyATS.txt (line 4)) (2019.11.28)
Requirement already satisfied: chardet==3.0.4 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from -r req_pyATS.txt (line 5)) (3.0.4)
Requirement already satisfied: dill==0.3.1.1 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from -r req_pyATS.txt (line 6)) (0.3.1.1)
Requirement already satisfied: distro==1.4.0 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from -r req_pyATS.txt (line 7)) (1.4.0)
Requirement already satisfied: idna==2.9 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from -r req_pyATS.txt (line 8)) (2.9)
Requirement already satisfied: Jinja2==2.11.1 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages/Jinja2-2.11.1-py3.7.egg (from -r req_pyATS.txt (line 9)) (2.11.1)
Requirement already satisfied: junit-xml==1.9 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from -r req_pyATS.txt (line 10)) (1.9)
Requirement already satisfied: MarkupSafe==1.1.1 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages/MarkupSafe-1.1.1-py3.7-linux-x86_64.egg (from -r req_pyATS.txt (line 11)) (1.1.1)
Requirement already satisfied: multidict==4.7.5 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from -r req_pyATS.txt (line 12)) (4.7.5)
Requirement already satisfied: pathspec==0.7.0 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from -r req_pyATS.txt (line 13)) (0.7.0)
Requirement already satisfied: psutil==5.7.0 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from -r req_pyATS.txt (line 14)) (5.7.0)
Requirement already satisfied: PyYAML==5.3.1 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from -r req_pyATS.txt (line 15)) (5.3.1)
Requirement already satisfied: requests==2.23.0 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from -r req_pyATS.txt (line 16)) (2.23.0)
Requirement already satisfied: six==1.14.0 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from -r req_pyATS.txt (line 17)) (1.14.0)
Requirement already satisfied: unicon==20.2 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from -r req_pyATS.txt (line 18)) (20.2)
Requirement already satisfied: unicon.plugins==20.2 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from -r req_pyATS.txt (line 19)) (20.2)
Requirement already satisfied: urllib3==1.25.8 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from -r req_pyATS.txt (line 20)) (1.25.8)
Requirement already satisfied: yamllint==1.21.0 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from -r req_pyATS.txt (line 21)) (1.21.0)
Requirement already satisfied: yarl==1.4.2 in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from -r req_pyATS.txt (line 22)) (1.4.2)
Collecting pyats==20.2.1 (from -r req_pyATS.txt (line 23))
Collecting pyats.aereport==20.2 (from -r req_pyATS.txt (line 24))
Collecting pyats.aetest==20.2 (from -r req_pyATS.txt (line 25))
Collecting pyats.async==20.2 (from -r req_pyATS.txt (line 26))
Collecting pyats.connections==20.2 (from -r req_pyATS.txt (line 27))
Collecting pyats.datastructures==20.2 (from -r req_pyATS.txt (line 28))
Collecting pyats.easypy==20.2 (from -r req_pyATS.txt (line 29))
Collecting pyats.kleenex==20.2 (from -r req_pyATS.txt (line 30))
Collecting pyats.log==20.2 (from -r req_pyATS.txt (line 31))
Collecting pyats.reporter==20.2.2 (from -r req_pyATS.txt (line 32))
Collecting pyats.results==20.2 (from -r req_pyATS.txt (line 33))
Collecting pyats.tcl==20.2 (from -r req_pyATS.txt (line 34))
Collecting pyats.topology==20.2 (from -r req_pyATS.txt (line 35))
Collecting pyats.utils==20.2 (from -r req_pyATS.txt (line 36))
Requirement already satisfied: setuptools in /home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages (from pyats.easypy==20.2->-r req_pyATS.txt (line 29)) (45.2.0)
Installing collected packages: pyats, pyats.results, pyats.datastructures, pyats.log, pyats.aereport, pyats.async, pyats.connections, pyats.topology, pyats.utils, pyats.aetest, pyats.kleenex, pyats.easypy, pyats.reporter, pyats.tcl
ERROR: Exception:
Traceback (most recent call last):
  File "/home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 407, in run
    use_user_site=options.use_user_site,
  File "/home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 928, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 461, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/home/XXX/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages/pip/_internal/wheel.py", line 434, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
```

Can someone help me out ?

**Comment by network-shark** [comment]
I'm not 100% , but I think the problem is a very very old glic version. Don't know if that is why the install fails , but I think so. 

```
>>> import unicon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/XXX/.pyenv/versions/py376/lib/python3.7/site-packages/unicon/__init__.py", line 9, in <module>
    from unicon.eal.expect import Spawn
  File "/home/XXX/.pyenv/versions/py376/lib/python3.7/site-packages/unicon/eal/__init__.py", line 22, in <module>
    from .utils import expect_log
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/XXX/.pyenv/versions/py376/lib/python3.7/site-packages/unicon/eal/utils.cp
ython-37m-x86_64-linux-gnu.so)
>>>
```

ldd --version

Should be bigger or equal to 2.14 ....

You can close the issue . Thank you

**Comment by simingy** [comment]
we build these packages using a docker container - i think it comes with modern glibc packages. Make sure you are using a recent version. Glad it's working!
