### ISSUE TITLE
Column 'Traffic Item' is missing from custom created 'GENIE' view

### ISSUE THREAD

**Issue by piervin-lab** [CiscoTestAutomation/pyats#55]
We are seeing 'Traffic Item' missing from 'GENIE' view after running dev.check_traffic_loss(check_iteration=1) after successfully starting traffic.

Output below:
OUTPUT BELOW:
 %GENIE-INFO: Displaying custom IxNetwork traffic statistics view 'GENIE' page...
 %GENIE-INFO: Custom IxNetwork traffic statistics view 'GENIE' is ready.
 Exception occured
 Unexpected error: <class 'genie.harness.exceptions.GenieTgnError'>
 Caught error in jobfile '/home/jcoulter/pyats_tests/bell_nokia/ixia_ova.py':
 %EASYPY-ERROR:
 Traceback (most recent call last):
 File "/home/jcoulter/pyats/lib64/python3.6/site-packages/genie/trafficgen/ixianative.py", line 1014, in create_traffic_streams_table
 assert item in headers
 AssertionError
 %EASYPY-ERROR:
 During handling of the above exception, another exception occurred:
 %EASYPY-ERROR:
 Traceback (most recent call last):
 File "/home/jcoulter/pyats_tests/bell_nokia/ixia_ova.py", line 86, in main
 noDataPlaneLoss()
 File "/home/jcoulter/pyats_tests/bell_nokia/ixia_ova.py", line 65, in noDataPlaneLoss
 dev.check_traffic_loss(check_iteration=1)
 File "src/pyats/async_/synchronize.py", line 117, in pyats.async_.synchronize.Lockable.locked.wrapped
 File "/home/jcoulter/pyats/lib64/python3.6/site-packages/genie/trafficgen/ixianative.py", line 129, in decorated
 return func(self, *args, **kwargs)
 File "/home/jcoulter/pyats/lib64/python3.6/site-packages/genie/trafficgen/ixianative.py", line 829, in check_traffic_loss
 clear_stats_time=clear_stats_time)
 File "src/pyats/async/synchronize.py", line 117, in pyats.async_.synchronize.Lockable.locked._wrapped
 File "/home/jcoulter/pyats/lib64/python3.6/site-packages/genie/trafficgen/ixianative.py", line 129, in decorated
 return func(self, *args, **kwargs)
 File "/home/jcoulter/pyats/lib64/python3.6/site-packages/genie/trafficgen/ixianative.py", line 1016, in create_traffic_streams_table
 raise GenieTgnError("Column '{}' is missing from custom created 'GENIE' view".format(item))
 genie.harness.exceptions.GenieTgnError: TGN-ERROR: Column 'Traffic Item' is missing from custom created 'GENIE' view

Job finished. Wrapping up...
 Creating archive file: /home/jcoulter/.pyats/archive/20-Aug/ixia_ova.2020Aug25_14:33:41.903450.zip
 +------------------------------------------------------------------------------+
 | !!! Exception Occured !!! |
 +------------------------------------------------------------------------------+
 Caught error in jobfile '/home/jcoulter/pyats_tests/bell_nokia/ixia_ova.py':
 %EASYPY-INFO:
 Traceback (most recent call last):
 File "/home/jcoulter/pyats/lib64/python3.6/site-packages/genie/trafficgen/ixianative.py", line 1014, in create_traffic_streams_table
 assert item in headers
 AssertionError
 %EASYPY-INFO:
 During handling of the above exception, another exception occurred:
 %EASYPY-INFO:
 Traceback (most recent call last):
 File "/home/jcoulter/pyats_tests/bell_nokia/ixia_ova.py", line 86, in main
 noDataPlaneLoss()
 File "/home/jcoulter/pyats_tests/bell_nokia/ixia_ova.py", line 65, in noDataPlaneLoss
 dev.check_traffic_loss(check_iteration=1)
 File "src/pyats/async_/synchronize.py", line 117, in pyats.async_.synchronize.Lockable.locked.wrapped
 File "/home/jcoulter/pyats/lib64/python3.6/site-packages/genie/trafficgen/ixianative.py", line 129, in decorated
 return func(self, *args, **kwargs)
 File "/home/jcoulter/pyats/lib64/python3.6/site-packages/genie/trafficgen/ixianative.py", line 829, in check_traffic_loss
 clear_stats_time=clear_stats_time)
 File "src/pyats/async/synchronize.py", line 117, in pyats.async_.synchronize.Lockable.locked._wrapped
 File "/home/jcoulter/pyats/lib64/python3.6/site-packages/genie/trafficgen/ixianative.py", line 129, in decorated
 return func(self, *args, **kwargs)
 File "/home/jcoulter/pyats/lib64/python3.6/site-packages/genie/trafficgen/ixianative.py", line 1016, in create_traffic_streams_table
 raise GenieTgnError("Column '{}' is missing from custom created 'GENIE' view".format(item))
 genie.harness.exceptions.GenieTgnError: TGN-ERROR: Column 'Traffic Item' is missing from custom created 'GENIE' view
 %EASYPY-INFO:

**Comment by KamyarZiabari** [comment]
Hello,

I am looking into issue and will get back you about this soon,

Thanks,
Kamyar

**Comment by KamyarZiabari** [comment]
Hi Again,

Just to give you the update on the case. The issue has been noted, and the fix soon be available as a beta to you. 
Please connect with us using pyats-support-ext@cisco.com if you have any other inquiry. 

Regards,
Kamyar

**Comment by lubnarasheed** [comment]
Hi @piervin-lab,

The error you're seeing is because the "Traffic Item" filter is not configured in your traffic streams. This filter is typically used to create a custom "Genie" traffic stats table for printing/traffic loss calculation

There are 2 possible solutions to this:

1. We've released a beta package with a fix to allow the user to disable checking for this filter (version 20.8.1b0). Once your venv is upgraded, you can call check_traffic_loss with the following extra argument and set it to ``True``:

``device.check_traffic_loss(check_iteration=1, disable_tracking=True)``

2. You can manually add this filter to your traffic stream configuration. It would require checking off 1 box shown below within the "Flow Tracking" configuration under "Edit Traffic Item":

The picture below illustrates where you can configure this filter manually on your IxNetwork application:

![image](https://user-images.githubusercontent.com/30269622/93509601-efa92a00-f8ed-11ea-8ef9-e5c63e23d720.png)

Please let us know if these solutions help resolve the issue

Regards,
Lubna Rasheed

**Comment by piervin-lab** [comment]
So thank  you for the update and direction. We have implemented the genie.trafficgen and pyats upgrade however, I am troubleshooting locating genie.trafficgen.ixianative.IxiaNative which is an alert we are seeing after the upgrade.

**Comment by jeaubin** [comment]
@piervin-lab  please re-open if you are still seeing the issue
