### ISSUE TITLE
Can not create tesbed file from ansible inventory

### ISSUE THREAD

**Issue by urskog84** [CiscoTestAutomation/pyats#97]
Hi i have trubbel generating testbed from an Ansible inventory

```
 pyats create testbed ansible --inventory-name prod.ini --output my_testbed.yml -vvvv
```

```
Traceback (most recent call last):
  File "/home/a002423/git/pyats-datacenter/venv/lib64/python3.6/site-packages/ansible/plugins/vars/host_group_vars.py", line 107, in get_vars
    found_files = loader.find_vars_files(opath, entity.name)
AttributeError: 'NoneType' object has no attribute 'find_vars_files'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/pyats/cli/base.py", line 207, in pyats.cli.base.Command.main
  File "src/pyats/cli/base.py", line 337, in pyats.cli.base.CommandWithSubcommands.run
  File "src/genie/cli/commands/create_testbed.py", line 34, in genie.cli.commands.create_testbed.CreateTestbed.run
  File "/home/a002423/git/pyats-datacenter/venv/lib64/python3.6/site-packages/pyats/contrib/creators/creator.py", line 208, in to_testbed_file
    testbed = self._generate()
  File "/home/a002423/git/pyats-datacenter/venv/lib64/python3.6/site-packages/pyats/contrib/creators/ansible.py", line 68, in _generate
    result = test.json_inventory(top=group)
  File "/home/a002423/git/pyats-datacenter/venv/lib64/python3.6/site-packages/ansible/cli/inventory.py", line 307, in json_inventory
    results = format_group(top)
  File "/home/a002423/git/pyats-datacenter/venv/lib64/python3.6/site-packages/ansible/cli/inventory.py", line 296, in format_group
    results.update(format_group(subgroup))
  File "/home/a002423/git/pyats-datacenter/venv/lib64/python3.6/site-packages/ansible/cli/inventory.py", line 296, in format_group
    results.update(format_group(subgroup))
  File "/home/a002423/git/pyats-datacenter/venv/lib64/python3.6/site-packages/ansible/cli/inventory.py", line 299, in format_group
    results[group.name]['vars'] = self._get_group_variables(group)
  File "/home/a002423/git/pyats-datacenter/venv/lib64/python3.6/site-packages/ansible/cli/inventory.py", line 201, in _get_group_variables
    res = combine_vars(res, get_vars_from_path(self.loader, context.CLIARGS['basedir'], [group], 'all'))
  File "/home/a002423/git/pyats-datacenter/venv/lib64/python3.6/site-packages/ansible/vars/plugins.py", line 75, in get_vars_from_path
    data = combine_vars(data, get_plugin_vars(loader, plugin, path, entities))
  File "/home/a002423/git/pyats-datacenter/venv/lib64/python3.6/site-packages/ansible/vars/plugins.py", line 26, in get_plugin_vars
    data = plugin.get_vars(loader, path, entities)
  File "/home/a002423/git/pyats-datacenter/venv/lib64/python3.6/site-packages/ansible/plugins/vars/host_group_vars.py", line 117, in get_vars
    raise AnsibleParserError(to_native(e))
ansible.errors.AnsibleParserError: 'NoneType' object has no attribute 'find_vars_files'


'NoneType' object has no attribute 'find_vars_files'
```

ansible folder strukture
```
.
├── ansible.cfg
├── `group_vars`
│   ├── access.yml
│   ├── all
│   │   ├── vars.yml
│   │   └── vault.yml
│   └── dist.yml
├── host_vars
│   ├── sw-dcacc-dh12-1a.yml
│   ├── sw-dcacc-dh12-1b.yml
│   ├── sw-dcacc-dh12-2a.yml
│   ├── sw-dcacc-dh12-2b.yml
│   ├── sw-dcacc-dh14-1a.yml
│   ├── sw-dcacc-dh14-1b.yml
│   ├── sw-dcacc-dh14-2a.yml
│   ├── sw-dcacc-dh14-2b.yml
│   ├── sw-dcdist-dh12-1a.yml
│   ├── sw-dcdist-dh12-1b.yml
│   ├── sw-dcdist-dh14-1a.yml
│   ├── sw-dcdist-dh14-1b.yml
│   ├── sw-nxos-lab-dh12-1a.yml
│   └── sw-nxos-lab-dh12-1b.yml
├── prod.ini
├── README.md
├── site.yml
└── test.ini
```

i have no problem to generate the json output with the ansible-inventry command
`ansible-inventory -i prod.ini --list all`

**Comment by LukasMcClelland** [comment]
Hello @urskog84, 

Thank you for bringing this issue to our attention. We will happily assign an engineer to this case. However, since pyats.contrib is a user contributed package, would you consider looking into it? 

https://github.com/CiscoTestAutomation/pyats.contrib/blob/master/src/pyats/contrib/creators/ansible.py
and 
https://github.com/CiscoTestAutomation/pyats.contrib/blob/master/src/pyats/contrib/creators/creator.py
are two places to start looking.

Thank you,
Lukas

**Comment by LukasMcClelland** [comment]
Hi @urskog84, have you had the chance to look into this issue?

If you haven't yet, please try
```
pyats create testbed ansible --inventory-name=prod.ini --output=my_testbed.yml
```

The parsing of CLI arguments is sometimes done differently in pyats.contrib package

**Comment by LukasMcClelland** [comment]
Hello again @urskog84, 

I've rerun the tests and looked into the code and things seem OK on our end. The command works as expected and tests pass. [Here's a link to the test file](https://github.com/CiscoTestAutomation/pyats.contrib/blob/master/src/pyats/contrib/creators/tests/test_ansible.py), so you can double check.

Please ensure that your 
- installation of pyATS is up to date
- your folder structure is what ansible/.ini file is expecting
- .ini file is correct
